### ISSUE TITLE
Add card tokenization for recurring billing

### ISSUE THREAD

**Issue by einkoro** [Strikewood/omnipay-first-atlantic-commerce#2]
http://omnipay.thephpleague.com/api/token-billing/

**Comment by karneaud** [comment]
What is the status of this @einkoro ? could [my fork](https://github.com/karneaud/omnipay-first-atlantic-commerce) be of assistance?

**Comment by einkoro** [comment]
@karneaud tokenization support was implemented back in 2015 but saved cards and subscriptions were never added to the woocommerce plug-in before development ceased from what I recall. Both the omnipay driver and the woocommerce plug-in are no longer maintained.

**Comment by karneaud** [comment]
@einkoro good to know. Also to note... I and a couple others are maintaining our own version of the omnipay driver for this particular gateway so If you need you can probably swap the driver source if needed.

My repo for the omnipay driver so far has implemented methods for the subscriptions endpoints.

I'm going to take a look into this and see what I can come up with. If you have any insights on this particular topic feel free to share.
