### ISSUE TITLE
Fatal error: Class 'Omnipay\Omnipay' not found

### ISSUE THREAD

**Issue by aaronbesson** [Strikewood/omnipay-first-atlantic-commerce#5]
I am getting the following error:
Fatal error: Class 'Omnipay\Omnipay' not found in /home/content/p3nexnas06_data03/92/2137392/html/wp-content/plugins/woocommerce-first-atlantic-commerce-master/includes/class-wc-gateway-fac.php on line 206

**Comment by einkoro** [comment]
Are you using composer to install WordPress + plugins? The WooCommerce FAC extension requires composer to install and manage the autoloader for dependencies and hasn't been packaged for installing through WordPress itself.

**Comment by aaronbesson** [comment]
HI, I am not sure how to install composer on wordpress? Can you point me in the right direction?

**Comment by einkoro** [comment]
Recommended reading regarding using Composer + WordPress:
- http://wpackagist.org
- https://roots.io/using-composer-with-wordpress/
- http://composer.rarst.net

You will need SSH access to use composer. If you are on shared hosting it might be a pain.

**Comment by aaronbesson** [comment]
I was now having a look at the roots.io site, i have the wordpress master file, but i am shared hosting, so this is going to be painful, thanks!

**Comment by einkoro** [comment]
You could also fork the plugin, download the dependencies and add them into the plugin using require() in the main plugin file to include them. That should work fine in theory as long as they are in the correct order. 

Probably easiest to use composer locally or in vagrant first and refer to the generated auto loader to get the requires in the right order.
